(in-package :cl-git-tree/commands/transport)

(defun apply-tar-xz-archive (archive-path dest-root)
  "Распаковывает bare-архив в целевую директорию dest-root, заменяя существующий mirror."
  (let* ((expanded-archive (cl-git-tree/fs:expand-home archive-path))
         (expanded-dest-root (uiop:ensure-directory-pathname (cl-git-tree/fs:expand-home dest-root)))
         (archive-name (file-namestring expanded-archive))
         (repo-name (if (and archive-name (>= (length archive-name) 7)
                             (string= ".tar.xz" (subseq archive-name (- (length archive-name) 7))))
                        (subseq archive-name 0 (- (length archive-name) 7))
                        archive-name))
         (bare-name (concatenate 'string repo-name ".git"))
         (dest-path (merge-pathnames bare-name expanded-dest-root))
         (temp-dir (uiop:ensure-directory-pathname
                    (merge-pathnames (make-pathname :directory (list :relative (format nil "tmp-git-tree-~A" (random 1000000))))
                                     (uiop:temporary-directory)))))
    (ensure-directories-exist expanded-dest-root)
    (format t "⬇ Распаковка ~A → ~A~%" archive-name (namestring dest-path))
    (multiple-value-bind (out err code)
        (uiop:run-program
         (list "tar" "-C" (namestring temp-dir) "-xJf" (namestring expanded-archive))
         :output :string
         :error-output :string
         :ignore-error-status t)
      (declare (ignore out))
      (if (zerop code)
          (let ((extracted (merge-pathnames bare-name temp-dir)))
            (if (probe-file extracted)
                (progn
                  (when (probe-file dest-path)
                    (uiop:delete-directory-tree dest-path :validate t))
                  (ensure-directories-exist expanded-dest-root)
                  (rename-file extracted dest-path)
                  (uiop:delete-directory-tree temp-dir :validate t)
                  (format t "✔ Импортировано: ~A~%" (namestring dest-path))
                  t)
                (progn
                  (uiop:delete-directory-tree temp-dir :validate t)
                  (format t "❌ Ошибка: в архиве не найден каталог ~A~%" bare-name)
                  nil)))
          (progn
            (uiop:delete-directory-tree temp-dir :validate t)
            (format t "❌ Ошибка распаковки:~%~A~%" err)
            nil)))))

(defun transport-import ()
  "Импортирует все найденные *.tar.xz из :url-xz в :url-git для локальных локаций."
  (let ((processed 0)
        (applied 0))
    (format t "⬇ Импорт архивов tar.xz из :url-xz в :url-git для всех локальных локаций~%~%")
    (dolist (loc-key (cl-git-tree/loc:all-location-keys))
      (let* ((loc (cl-git-tree/loc:find-location loc-key))
             (url-xz (and loc (cl-git-tree/loc:<location>-url-xz loc)))
             (url-git (and loc (cl-git-tree/loc:<location>-url-git loc)))
             (provider (and loc (cl-git-tree/loc:<location>-provider loc))))
        (when (and loc url-xz url-git)
          (let* ((xz-dir (uiop:ensure-directory-pathname (cl-git-tree/fs:expand-home url-xz)))
                 (archives (directory (merge-pathnames #p"*.tar.xz" xz-dir))))
            (when archives
              (format t "Локация ~A (провайдер ~A)~%" loc-key provider)
              (dolist (archive archives)
                (incf processed)
                (format t "  • ~A~%" (namestring archive))
                (if (apply-tar-xz-archive archive url-git)
                    (incf applied)
                    (format t "    ⚠️  Пропущено из-за ошибки~%"))))))))
    (format t "~%=== Итог импорта ===~%")
    (format t "Обработано архивов: ~A~%" processed)
    (format t "Импортировано: ~A~%" applied)))
